name: 'Build Android App'

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make secrets available to Gradle
        run: |
          echo "EWAY_API_KEY=${{ secrets.EWAY_API_KEY }}" >> $GITHUB_ENV
          echo "EWAY_API_PASSWORD=${{ secrets.EWAY_API_PASSWORD }}" >> $GITHUB_ENV
          echo "EWAY_PUBLIC_KEY=${{ secrets.EWAY_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "EWAY_END_POINT=${{ secrets.EWAY_END_POINT }}" >> $GITHUB_ENV

      - name: Run Gradle build
        run: ./gradlew build
        env:
          EWAY_API_KEY: ${{ env.EWAY_API_KEY }}
          EWAY_API_PASSWORD: ${{ env.EWAY_API_PASSWORD }}
          EWAY_PUBLIC_KEY: ${{ env.EWAY_PUBLIC_KEY }}
          EWAY_END_POINT: ${{ env.EWAY_END_POINT }}

      - name: Change wrapper permissions
        run: chmod +x ./android/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: |
          cd ./android
          ./gradlew assembleRelease

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./android/app/build/outputs/apk/release/app-release.apk
          retention-days: 3
